src/Entity/Order.php
<?php

namespace App\Entity;

use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\ORM\Mapping as ORM;
use Doctrine\ORM\PersistentCollection;

/**
 * Product
 *
 * @ORM\Entity()
 * @ORM\Table(name="orders")
 */
class Order
{
    /**
     * @ORM\Column(name="id", type="integer", nullable=false, options={"unsigned"=true})
     * @ORM\Id
     * @ORM\GeneratedValue(strategy="IDENTITY")
     */
    private $id;

    /**
     * @ORM\Column(name="created_at", type="datetime", nullable=false)
     */
    private $createdAt;

    /**
     * @ORM\Column(name="status", type="text", length=255, nullable=false)
     */
    private $status;

    /**
     * @ORM\OneToMany(targetEntity="\App\Entity\OrderItem", mappedBy="order", cascade={"persist"})
     */
    private $items;

    public function __construct()
    {
        $this->createdAt = new \DateTime();
        $this->items = new ArrayCollection();
        $this->status = 'new';
    }


    public function getId(): ?int
    {
        return $this->id;
    }

    public function setId(int $id): self
    {
        $this->id = $id;

        return $this;
    }

    public function getCreatedAt(): \DateTime
    {
        return $this->createdAt;
    }

    public function setCreatedAt(\DateTime $createdAt): self
    {
        $this->createdAt = $createdAt;

        return $this;
    }

    public function getStatus(): string
    {
        return $this->status;
    }

    public function setStatus(string $status): self
    {
        $this->status = $status;

        return $this;
    }

    public function getStatusTitle(): ?string
    {
        return [
            'new' => 'Новый',
            'pay' => 'Оплачен',
        ][$this->status];
    }

    public function getItems(): PersistentCollection
    {
        return $this->items;
    }

    public function addItem(OrderItem $orderItem)
    {
        $this->items->add($orderItem);

        return $this;
    }

    public function getSum(): int
    {
        $sum = 0;
        $this->items->map(
            function (OrderItem $orderItem) use (&$sum) {
                $sum += $orderItem->getSum();
            }
        );

        return $sum;
    }
}

templates/pages/cart.html.twig
{% extends "layout.html.twig" %}

{% block content %}
    <article id="pageHome">

        <section class="homeText">
            <h1>Shoppong cart</h1>
            {% include "cart/items.html.twig" %}
        </section>
    </article>
{% endblock %}

templates/pages/home.html.twig
{% extends "layout.html.twig" %}

{% block content %}
    <article id="pageHome">

        <section class="homeText">
            <h1>Small e-shop</h1>
            {% include "catalog/category/items.html.twig" %}
        </section>
    </article>
{% endblock %}

templates/pages/order.html.twig
{% extends "layout.html.twig" %}

{% block content %}
    <article id="pageOrder">

        <section>
            <h1>Order {{ order.id }} [{{ order.statusTitle }}] [{{ order.createdAt|date }}]</h1>
            <section>
                <table id="orderItems">
                    <thead>
                    <tr>
                        <th colspan="2">Состав заказа</th>
                        <th>Цена</th>
                        <th>Кол-во</th>
                        <th>Сумма</th>
                    </tr>
                    </thead>

                    <tbody>
                    {% for item in order.items %}
                        {% set product = item.product %}
                        <tr class="item">
                            <td>
                                {% if product.image %}<a href="#" class="img"><img src="{{ product.image }}" alt="{{ product.name }}"></a>{% endif %}
                            </td>
                            <td >
                                <i class="id">{{ product.id }}</i>
                                <a href="#" class="name">{{ product.name }}</a>
                            </td>
                            <td class="price rub">{{ item.price|price}}</td>
                            <td class="cnt">{{ item.count }} шт.</td>
                            <td class="sum rub">{{ item.sum|price }}</td>
                        </tr>
                    {% endfor %}
                    </tbody>

                    <tfoot>
                    <tr>
                        <td colspan="4">Итого:</td>
                        <td id="orderSum" class="rub">{{ order.sum|price }}</td>
                        <td></td>
                    </tr>
                    <tr>
                        <td colspan="3" id="result"></td>
                        <td colspan="2">{% if order.status is same as('new') %}<a href="#" id="payOrder" data-id="{{ order.id }}">Оплатить</a>{% endif %}</td>
                        <td></td>
                    </tr>
                    </tfoot>
                </table>
            </section>
        </section>
    </article>
{% endblock %}